In [1]:
import tensorflow as tf

In [2]:
print(("TensorFlow version: {0}").format(tf.__version__))

TensorFlow version: 2.15.0


In [7]:
# Constant tensor A
a = tf.constant([[4, 3],
                [6, 1]])

In [10]:
v = tf.Variable([[3,1],
                [5,2]])

b = tf.constant([[7, 8],
                [4, 5]])

print(v)
b

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]])>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]])>

In [12]:
# Concatenate columns
ab_concatenated = tf.concat(values = [a, b], axis = 1)
ab_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]])>

In [13]:
ab_concatenated = tf.concat(values = [a, b], axis = 0)
ab_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]])>

In [19]:
tensor = tf.random.uniform(shape = [3, 4], dtype = tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.45883632, 0.7660476 , 0.61051774, 0.26820362],
       [0.9750439 , 0.16107333, 0.25231457, 0.65323055],
       [0.80763745, 0.6980587 , 0.90824485, 0.9017751 ]], dtype=float32)>

In [20]:
reshaped_tensor = tf.reshape(tensor = tensor, shape = [4, 3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.45883632, 0.7660476 , 0.61051774],
       [0.26820362, 0.9750439 , 0.16107333],
       [0.25231457, 0.65323055, 0.80763745],
       [0.6980587 , 0.90824485, 0.9017751 ]], dtype=float32)>

In [23]:
# Recasting a tensor

tensor = tf.constant([[4.6, 4.2],
                     [7.5, 3.6],
                     [2.7, 9.4],
                     [6.7, 8.3]],
                    dtype = tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)
tensor_as_int

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 4],
       [7, 3],
       [2, 9],
       [6, 8]])>

In [25]:
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [4, 3, 9, 8]])>

In [26]:
# Matrix multiplication of tensors

a = tf.constant([[5, 8],
                [3, 9]])

v = tf.constant([[4],
                [2]])

av = tf.matmul(a, v)
av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]])>

In [27]:
# Element-wise multiplication

av = tf.multiply(a, v)
av

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]])>

In [31]:
# Creating an identity matrix

a = tf.constant([[4, 9],
                [5, 6],
                [1, 8]])

rows, columns = a.shape
print("Rows:", rows, "| Columns:", columns)
a_identity = tf.eye(num_rows = rows, num_columns = columns, dtype = tf.int32)
a_identity

Rows: 3 | Columns: 2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]])>